<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Content/Branding/KeyLearner.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Studio/**/*.cs" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.2.1105" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.2.1105" />
    <PackageReference Include="System.Speech" Version="9.0.0" />

    <MonoGameContentReference Include="Content/Content.mgcb" />
    <None Update="Content/Voice/*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Content/Branding/*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Content/Fonts/*-OFL.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Content/Effects/*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Content/Icons/*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="data/*_dictionary.csv" CopyToOutputDirectory="PreserveNewest" />
    <None Update="data/private_dictionary.csv" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>
